#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Code is generated by Telerik Data Access Service Wizard
// using Astoria3DataService.tt template

namespace lahman_webservice
{
	using System.Data.Services;
	using System.Data.Services.Common;
	using Telerik.OpenAccess.DataServices;
	using System;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.Serialization;

	/// <summary>
	/// Adventureworks service class handler.
	/// </summary>
	[System.ServiceModel.ServiceBehavior(IncludeExceptionDetailInFaults = true)]
	public partial class Adventureworks : OpenAccessDataService<lahman_odata.Adventureworks>
	{
	    /// <summary>
	    /// Initializes the service.
	    /// </summary>
	    /// <param name="config">The configuration object.</param>
	    public static void InitializeService(DataServiceConfiguration config)
	    {
	        config.SetEntitySetAccessRule("dimproducts", EntitySetRights.AllRead);
	
	        // TODO: Set service behavior configuration options
	        // Examples:
	        // config.DataServiceBehavior.AcceptCountRequests = true;
	        // config.DataServiceBehavior.AcceptProjectionRequests = true;
	        config.DataServiceBehavior.MaxProtocolVersion = DataServiceProtocolVersion.V3;
	    }
	}
}
#pragma warning restore 1591
